### ISSUE TITLE
Licence request - MIT or BSD or Beerware

### ISSUE THREAD

**Issue by RogerHardiman** [jordicenzano/h264simpleCoder#1]
Hi
I wanted to port your H264 encoder over to C# to include in the SharpRTSP project so I have a simple H264 encoder written in .Net.
(I'm aware that as a lossless conversion to H264 the data size is huge)

Currently I use Cardinal Peak's Tiny H264 in the SharpRTSP project but noticed you generate the SPS and PPS instead of having hard coded values.

Is it OK to use take and port your code - there was no licence listed and SharpRTSP is MIT licensed.

Thanks
Roger

**Comment by jordicenzano** [comment]
Hi Roger, no problem if you want to use my code.

Regards
Jordi

**Comment by jordicenzano** [comment]
And thanks for your contributions
