### ISSUE TITLE
Bug in SPS creation and Slice Header

### ISSUE THREAD

**Issue by RogerHardiman** [jordicenzano/h264simpleCoder#5]
Hi
Why trying to work out why Apple's H264 decoder would not play your H264 stream I found a few bugs in H264SimpleCoder  

**SPS creation**  
Near the end of the SPS is this code
```
	addbits(0x0,1); // frame_mbs_only_flag
	addbits(0x1,1); // rbsp stop bit
```
The frame_mbs_only_flag is an error. It is in your SPS twice and it already comes earlier in the SPS.

**Comment by RogerHardiman** [comment]
Why trying to work out why Apple's H264 decoder would not play your H264 stream I found a few bugs in H264SimpleCoder

**SPS creation**
Near the end of the SPS is this code
```
	addbits(0x0,1); // frame_mbs_only_flag
	addbits(0x1,1); // rbsp stop bit
```
The frame_mbs_only_flag is an error. It is in your SPS twice and it already comes earlier in the SPS.


**Slice Header**
The other bug is in the Slice Header.
There is a cFrameNum.
The ITU H264 spec says cFrameNum must be Zero for IDR frames.
Currently it is set to lFrameNum %16
I had to change it to ```cFrameNum = 0``` so the video would work on an Apple Mac with the SecuritySpy CCTV software

**Comment by jordicenzano** [comment]
Thanks a lot for your PR. At first glance your changes makes sense, let me take a deeper look and I'll merge them.

**Comment by RogerHardiman** [comment]
Hi
I agree that having a deeper look is a good idea. This was the first time I'd read parts of the ITU H264 spec so I may have missed something.

**Comment by RogerHardiman** [comment]
the PR was merged so this issue is now closed
